name: beaver
description: A little logger for Dart. Structured, server-side logging with zone-based context propagation.
version: 2.0.0
homepage: https://github.com/kirklink/beaver
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chary:
    path: ../chary/chary

dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.1
